TRUNCATE TABLE HOLIDAY RESTART IDENTITY;
TRUNCATE TABLE RESTAURANT_NOTIFICATION RESTART IDENTITY;
TRUNCATE TABLE RESERVATION RESTART IDENTITY;
TRUNCATE TABLE RESTAURANT RESTART IDENTITY;
TRUNCATE TABLE OWNER RESTART IDENTITY;
TRUNCATE TABLE MEMBER RESTART IDENTITY;